"""empty message

Revision ID: 31259d1ba964
Revises: 8af9c4190b00
Create Date: 2019-12-01 20:09:23.111396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31259d1ba964'
down_revision = '8af9c4190b00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('movie_genre', sa.Text(), nullable=True))
    op.create_index(op.f('ix_movies_movie_genre'), 'movies', ['movie_genre'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_movie_genre'), table_name='movies')
    op.drop_column('movies', 'movie_genre')
    # ### end Alembic commands ###
