"""empty message

Revision ID: b42bf03bffea
Revises: d5fd95f1ca41
Create Date: 2019-12-30 09:45:10.012611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b42bf03bffea'
down_revision = 'd5fd95f1ca41'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movies', sa.Column('avg_rating', sa.Float(), nullable=True))
    op.create_index(op.f('ix_movies_avg_rating'), 'movies', ['avg_rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_movies_avg_rating'), table_name='movies')
    op.drop_column('movies', 'avg_rating')
    # ### end Alembic commands ###
