"""empty message

Revision ID: d5fd95f1ca41
Revises: 31259d1ba964
Create Date: 2019-12-27 21:24:54.770206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd5fd95f1ca41'
down_revision = '31259d1ba964'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_movies_movie_name', table_name='movies')
    op.create_index(op.f('ix_movies_movie_name'), 'movies', ['movie_name'], unique=False)
    op.drop_index('ix_reviews_comment', table_name='reviews')
    op.create_index(op.f('ix_reviews_comment'), 'reviews', ['comment'], unique=False)
    op.drop_index('ix_reviews_rating', table_name='reviews')
    op.create_index(op.f('ix_reviews_rating'), 'reviews', ['rating'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_reviews_rating'), table_name='reviews')
    op.create_index('ix_reviews_rating', 'reviews', ['rating'], unique=1)
    op.drop_index(op.f('ix_reviews_comment'), table_name='reviews')
    op.create_index('ix_reviews_comment', 'reviews', ['comment'], unique=1)
    op.drop_index(op.f('ix_movies_movie_name'), table_name='movies')
    op.create_index('ix_movies_movie_name', 'movies', ['movie_name'], unique=1)
    # ### end Alembic commands ###
